# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import asset360_rust
import builtins
import linkml_meta

def get_all_classes_by_type_designator_and_schema(schemaview:asset360_rust.SchemaView, only_registered:builtins.bool=True, only_default:builtins.bool=True) -> dict[str, linkml_meta.ClassDefinition]:
    r"""
    Return every class keyed by its resolved type designator.
    
    * `schemaview` – existing [`SchemaView`] instance to inspect.
    * `only_registered` – require the ``data.infrabel.be/asset360/managed``
      annotation to be truthy.
    * `only_default` – restrict to each class' primary type designator instead of
      all accepted aliases.
    """

